import type { Item } from "../../shared/types";

export const defaultItems: Array<Item> = [
    { "name": "accumulator", "order": "e[accumulator]-a[accumulator]", "subgroup": "b", "group": "production", "stackSize": 50, "type": "accumulator", "tileWidth": 2, "tileHeight": 2 },
    { "name": "advanced-circuit", "order": "f[advanced-circuit]", "subgroup": "g", "group": "intermediate-products", "stackSize": 200, "type": "item" },
    { "name": "arithmetic-combinator", "order": "c[combinators]-a[arithmetic-combinator]", "subgroup": "h", "group": "logistics", "stackSize": 50, "type": "arithmetic-combinator", "tileWidth": 1, "tileHeight": 2 },
    { "name": "artillery-shell", "order": "d[explosive-cannon-shell]-d[artillery]", "subgroup": "b", "group": "combat", "stackSize": 1, "type": "ammo" },
    { "name": "artillery-targeting-remote", "order": "b[turret]-d[artillery-turret]-b[remote]", "subgroup": "g", "group": "combat", "stackSize": 1, "type": "capsule" },
    { "name": "artillery-turret", "order": "b[turret]-d[artillery-turret]-a[turret]", "subgroup": "g", "group": "combat", "stackSize": 10, "type": "artillery-turret", "tileWidth": 3, "tileHeight": 3 },
    { "name": "artillery-wagon", "order": "a[train-system]-i[artillery-wagon]", "subgroup": "e", "group": "logistics", "stackSize": 5, "type": "artillery-wagon", "tileWidth": 2, "tileHeight": 5 },
    { "name": "assembling-machine-1", "order": "a[assembling-machine-1]", "subgroup": "e", "group": "production", "stackSize": 50, "type": "assembling-machine", "tileWidth": 3, "tileHeight": 3 },
    { "name": "assembling-machine-2", "order": "b[assembling-machine-2]", "subgroup": "e", "group": "production", "stackSize": 50, "type": "assembling-machine", "tileWidth": 3, "tileHeight": 3 },
    { "name": "assembling-machine-3", "order": "c[assembling-machine-3]", "subgroup": "e", "group": "production", "stackSize": 50, "type": "assembling-machine", "tileWidth": 3, "tileHeight": 3 },
    { "name": "atomic-bomb", "order": "d[rocket-launcher]-c[atomic-bomb]", "subgroup": "b", "group": "combat", "stackSize": 10, "type": "ammo" },
    { "name": "automation-science-pack", "order": "a[automation-science-pack]", "subgroup": "h", "group": "intermediate-products", "stackSize": 200, "type": "tool" },
    { "name": "battery", "order": "h[battery]", "subgroup": "c", "group": "intermediate-products", "stackSize": 200, "type": "item" },
    { "name": "battery-equipment", "order": "b[battery]-a[battery-equipment]", "subgroup": "e", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "battery-mk2-equipment", "order": "b[battery]-b[battery-equipment-mk2]", "subgroup": "e", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "beacon", "order": "a[beacon]", "subgroup": "f", "group": "production", "stackSize": 10, "type": "beacon", "tileWidth": 3, "tileHeight": 3 },
    { "name": "belt-immunity-equipment", "order": "c[belt-immunity]-a[belt-immunity]", "subgroup": "e", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "big-electric-pole", "order": "a[energy]-c[big-electric-pole]", "subgroup": "d", "group": "logistics", "stackSize": 50, "type": "electric-pole", "tileWidth": 2, "tileHeight": 2 },
    { "name": "boiler", "order": "b[steam-power]-a[boiler]", "subgroup": "b", "group": "production", "stackSize": 50, "type": "boiler", "tileWidth": 3, "tileHeight": 2 },
    { "name": "burner-inserter", "order": "a[burner-inserter]", "subgroup": "c", "group": "logistics", "stackSize": 50, "type": "inserter", "tileWidth": 1, "tileHeight": 1 },
    { "name": "burner-mining-drill", "order": "a[items]-a[burner-mining-drill]", "subgroup": "c", "group": "production", "stackSize": 50, "type": "mining-drill", "tileWidth": 2, "tileHeight": 2 },
    { "name": "cannon-shell", "order": "d[cannon-shell]-a[basic]", "subgroup": "b", "group": "combat", "stackSize": 200, "type": "ammo" },
    { "name": "car", "order": "b[personal-transport]-a[car]", "subgroup": "f", "group": "logistics", "stackSize": 1, "type": "car", "tileWidth": 2, "tileHeight": 2 },
    { "name": "cargo-wagon", "order": "a[train-system]-g[cargo-wagon]", "subgroup": "e", "group": "logistics", "stackSize": 5, "type": "cargo-wagon", "tileWidth": 2, "tileHeight": 5 },
    { "name": "centrifuge", "order": "g[centrifuge]", "subgroup": "e", "group": "production", "stackSize": 50, "type": "assembling-machine", "tileWidth": 3, "tileHeight": 3 },
    { "name": "chemical-plant", "order": "e[chemical-plant]", "subgroup": "e", "group": "production", "stackSize": 10, "type": "assembling-machine", "tileWidth": 3, "tileHeight": 3 },
    { "name": "chemical-science-pack", "order": "d[chemical-science-pack]", "subgroup": "h", "group": "intermediate-products", "stackSize": 200, "type": "tool" },
    { "name": "cliff-explosives", "order": "d[cliff-explosives]", "subgroup": "i", "group": "logistics", "stackSize": 20, "type": "capsule" },
    { "name": "cluster-grenade", "order": "a[grenade]-b[cluster]", "subgroup": "c", "group": "combat", "stackSize": 100, "type": "capsule" },
    { "name": "coal", "order": "b[coal]", "subgroup": "b", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "combat-shotgun", "order": "b[shotgun]-a[combat]", "subgroup": "a", "group": "combat", "stackSize": 5, "type": "gun" },
    { "name": "concrete", "order": "b[concrete]-a[plain]", "subgroup": "i", "group": "logistics", "stackSize": 100, "type": "item" },
    { "name": "constant-combinator", "order": "c[combinators]-c[constant-combinator]", "subgroup": "h", "group": "logistics", "stackSize": 50, "type": "constant-combinator", "tileWidth": 1, "tileHeight": 1 },
    { "name": "construction-robot", "order": "a[robot]-b[construction-robot]", "subgroup": "g", "group": "logistics", "stackSize": 50, "type": "construction-robot", "tileWidth": 0, "tileHeight": 0 },
    { "name": "copper-cable", "order": "a[copper-cable]", "subgroup": "g", "group": "intermediate-products", "stackSize": 200, "type": "item" },
    { "name": "copper-ore", "order": "f[copper-ore]", "subgroup": "b", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "copper-plate", "order": "c[copper-plate]", "subgroup": "c", "group": "intermediate-products", "stackSize": 100, "type": "item" },
    { "name": "crude-oil", "order": "a[fluid]-b[crude-oil]", "subgroup": "a", "group": "fluids", "type": "fluid" },
    { "name": "decider-combinator", "order": "c[combinators]-b[decider-combinator]", "subgroup": "h", "group": "logistics", "stackSize": 50, "type": "decider-combinator", "tileWidth": 1, "tileHeight": 2 },
    { "name": "defender-capsule", "order": "d[defender-capsule]", "subgroup": "c", "group": "combat", "stackSize": 100, "type": "capsule" },
    { "name": "destroyer-capsule", "order": "f[destroyer-capsule]", "subgroup": "c", "group": "combat", "stackSize": 100, "type": "capsule" },
    { "name": "discharge-defense-equipment", "order": "b[active-defense]-b[discharge-defense-equipment]-a[equipment]", "subgroup": "f", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "discharge-defense-remote", "order": "b[active-defense]-b[discharge-defense-equipment]-b[remote]", "subgroup": "f", "group": "combat", "stackSize": 1, "type": "capsule" },
    { "name": "distractor-capsule", "order": "e[defender-capsule]", "subgroup": "c", "group": "combat", "stackSize": 100, "type": "capsule" },
    { "name": "effectivity-module", "order": "c[effectivity]-a[effectivity-module-1]", "subgroup": "f", "group": "production", "stackSize": 50, "type": "module" },
    { "name": "effectivity-module-2", "order": "c[effectivity]-b[effectivity-module-2]", "subgroup": "f", "group": "production", "stackSize": 50, "type": "module" },
    { "name": "effectivity-module-3", "order": "c[effectivity]-c[effectivity-module-3]", "subgroup": "f", "group": "production", "stackSize": 50, "type": "module" },
    { "name": "electric-engine-unit", "order": "i[electric-engine-unit]", "subgroup": "g", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "electric-furnace", "order": "c[electric-furnace]", "subgroup": "d", "group": "production", "stackSize": 50, "type": "furnace", "tileWidth": 3, "tileHeight": 3 },
    { "name": "electric-mining-drill", "order": "a[items]-b[electric-mining-drill]", "subgroup": "c", "group": "production", "stackSize": 50, "type": "mining-drill", "tileWidth": 3, "tileHeight": 3 },
    { "name": "electronic-circuit", "order": "e[electronic-circuit]", "subgroup": "g", "group": "intermediate-products", "stackSize": 200, "type": "item" },
    { "name": "empty-barrel", "order": "d[empty-barrel]", "subgroup": "g", "group": "intermediate-products", "stackSize": 10, "type": "item" },
    { "name": "energy-shield-equipment", "order": "a[shield]-a[energy-shield-equipment]", "subgroup": "f", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "energy-shield-mk2-equipment", "order": "a[shield]-b[energy-shield-equipment-mk2]", "subgroup": "f", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "engine-unit", "order": "h[engine-unit]", "subgroup": "g", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "exoskeleton-equipment", "order": "d[exoskeleton]-a[exoskeleton-equipment]", "subgroup": "e", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "explosive-cannon-shell", "order": "d[cannon-shell]-c[explosive]", "subgroup": "b", "group": "combat", "stackSize": 200, "type": "ammo" },
    { "name": "explosive-rocket", "order": "d[rocket-launcher]-b[explosive]", "subgroup": "b", "group": "combat", "stackSize": 200, "type": "ammo" },
    { "name": "explosive-uranium-cannon-shell", "order": "d[explosive-cannon-shell]-c[uranium]", "subgroup": "b", "group": "combat", "stackSize": 200, "type": "ammo" },
    { "name": "explosives", "order": "j[explosives]", "subgroup": "c", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "express-splitter", "order": "c[splitter]-c[express-splitter]", "subgroup": "b", "group": "logistics", "stackSize": 50, "type": "splitter", "tileWidth": 2, "tileHeight": 1 },
    { "name": "express-transport-belt", "order": "a[transport-belt]-c[express-transport-belt]", "subgroup": "b", "group": "logistics", "stackSize": 100, "type": "transport-belt", "tileWidth": 1, "tileHeight": 1 },
    { "name": "express-underground-belt", "order": "b[underground-belt]-c[express-underground-belt]", "subgroup": "b", "group": "logistics", "stackSize": 50, "type": "underground-belt", "tileWidth": 1, "tileHeight": 1 },
    { "name": "fast-inserter", "order": "d[fast-inserter]", "subgroup": "c", "group": "logistics", "stackSize": 50, "type": "inserter", "tileWidth": 1, "tileHeight": 1 },
    { "name": "fast-splitter", "order": "c[splitter]-b[fast-splitter]", "subgroup": "b", "group": "logistics", "stackSize": 50, "type": "splitter", "tileWidth": 2, "tileHeight": 1 },
    { "name": "fast-transport-belt", "order": "a[transport-belt]-b[fast-transport-belt]", "subgroup": "b", "group": "logistics", "stackSize": 100, "type": "transport-belt", "tileWidth": 1, "tileHeight": 1 },
    { "name": "fast-underground-belt", "order": "b[underground-belt]-b[fast-underground-belt]", "subgroup": "b", "group": "logistics", "stackSize": 50, "type": "underground-belt", "tileWidth": 1, "tileHeight": 1 },
    { "name": "filter-inserter", "order": "e[filter-inserter]", "subgroup": "c", "group": "logistics", "stackSize": 50, "type": "inserter", "tileWidth": 1, "tileHeight": 1 },
    { "name": "firearm-magazine", "order": "a[basic-clips]-a[firearm-magazine]", "subgroup": "b", "group": "combat", "stackSize": 200, "type": "ammo" },
    { "name": "flamethrower", "order": "e[flamethrower]", "subgroup": "a", "group": "combat", "stackSize": 5, "type": "gun" },
    { "name": "flamethrower-ammo", "order": "e[flamethrower]", "subgroup": "b", "group": "combat", "stackSize": 100, "type": "ammo" },
    { "name": "flamethrower-turret", "order": "b[turret]-c[flamethrower-turret]", "subgroup": "g", "group": "combat", "stackSize": 50, "type": "fluid-turret", "tileWidth": 2, "tileHeight": 3 },
    { "name": "fluid-wagon", "order": "a[train-system]-h[fluid-wagon]", "subgroup": "e", "group": "logistics", "stackSize": 5, "type": "fluid-wagon", "tileWidth": 2, "tileHeight": 5 },
    { "name": "flying-robot-frame", "order": "l[flying-robot-frame]", "subgroup": "g", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "fusion-reactor-equipment", "order": "a[energy-source]-b[fusion-reactor]", "subgroup": "e", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "gate", "order": "a[wall]-b[gate]", "subgroup": "g", "group": "combat", "stackSize": 50, "type": "gate", "tileWidth": 1, "tileHeight": 1 },
    { "name": "green-wire", "order": "b[wires]-b[green-wire]", "subgroup": "h", "group": "logistics", "stackSize": 200, "type": "item" },
    { "name": "grenade", "order": "a[grenade]-a[normal]", "subgroup": "c", "group": "combat", "stackSize": 100, "type": "capsule" },
    { "name": "gun-turret", "order": "b[turret]-a[gun-turret]", "subgroup": "g", "group": "combat", "stackSize": 50, "type": "ammo-turret", "tileWidth": 2, "tileHeight": 2 },
    { "name": "hazard-concrete", "order": "b[concrete]-b[hazard]", "subgroup": "i", "group": "logistics", "stackSize": 100, "type": "item" },
    { "name": "heat-exchanger", "order": "f[nuclear-energy]-c[heat-exchanger]", "subgroup": "b", "group": "production", "stackSize": 50, "type": "boiler", "tileWidth": 3, "tileHeight": 2 },
    { "name": "heat-pipe", "order": "f[nuclear-energy]-b[heat-pipe]", "subgroup": "b", "group": "production", "stackSize": 50, "type": "heat-pipe", "tileWidth": 1, "tileHeight": 1 },
    { "name": "heavy-armor", "order": "b[heavy-armor]", "subgroup": "d", "group": "combat", "stackSize": 1, "type": "armor" },
    { "name": "heavy-oil", "order": "a[fluid]-c[heavy-oil]", "subgroup": "a", "group": "fluids", "type": "fluid" },
    { "name": "inserter", "order": "b[inserter]", "subgroup": "c", "group": "logistics", "stackSize": 50, "type": "inserter", "tileWidth": 1, "tileHeight": 1 },
    { "name": "iron-chest", "order": "a[items]-b[iron-chest]", "subgroup": "a", "group": "logistics", "stackSize": 50, "type": "container", "tileWidth": 1, "tileHeight": 1 },
    { "name": "iron-gear-wheel", "order": "c[iron-gear-wheel]", "subgroup": "g", "group": "intermediate-products", "stackSize": 100, "type": "item" },
    { "name": "iron-ore", "order": "e[iron-ore]", "subgroup": "b", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "iron-plate", "order": "b[iron-plate]", "subgroup": "c", "group": "intermediate-products", "stackSize": 100, "type": "item" },
    { "name": "iron-stick", "order": "b[iron-stick]", "subgroup": "g", "group": "intermediate-products", "stackSize": 100, "type": "item" },
    { "name": "lab", "order": "g[lab]", "subgroup": "e", "group": "production", "stackSize": 10, "type": "lab", "tileWidth": 3, "tileHeight": 3 },
    { "name": "land-mine", "order": "f[land-mine]", "subgroup": "a", "group": "combat", "stackSize": 100, "type": "land-mine", "tileWidth": 1, "tileHeight": 1 },
    { "name": "landfill", "order": "c[landfill]-a[dirt]", "subgroup": "i", "group": "logistics", "stackSize": 100, "type": "item" },
    { "name": "laser-turret", "order": "b[turret]-b[laser-turret]", "subgroup": "g", "group": "combat", "stackSize": 50, "type": "electric-turret", "tileWidth": 2, "tileHeight": 2 },
    { "name": "light-armor", "order": "a[light-armor]", "subgroup": "d", "group": "combat", "stackSize": 1, "type": "armor" },
    { "name": "light-oil", "order": "a[fluid]-d[light-oil]", "subgroup": "a", "group": "fluids", "type": "fluid" },
    { "name": "locomotive", "order": "a[train-system]-f[locomotive]", "subgroup": "e", "group": "logistics", "stackSize": 5, "type": "locomotive", "tileWidth": 2, "tileHeight": 6 },
    { "name": "logistic-chest-active-provider", "order": "b[storage]-c[logistic-chest-active-provider]", "subgroup": "g", "group": "logistics", "stackSize": 50, "type": "logistic-container", "tileWidth": 1, "tileHeight": 1 },
    { "name": "logistic-chest-buffer", "order": "b[storage]-d[logistic-chest-buffer]", "subgroup": "g", "group": "logistics", "stackSize": 50, "type": "logistic-container", "tileWidth": 1, "tileHeight": 1 },
    { "name": "logistic-chest-passive-provider", "order": "b[storage]-c[logistic-chest-passive-provider]", "subgroup": "g", "group": "logistics", "stackSize": 50, "type": "logistic-container", "tileWidth": 1, "tileHeight": 1 },
    { "name": "logistic-chest-requester", "order": "b[storage]-e[logistic-chest-requester]", "subgroup": "g", "group": "logistics", "stackSize": 50, "type": "logistic-container", "tileWidth": 1, "tileHeight": 1 },
    { "name": "logistic-chest-storage", "order": "b[storage]-c[logistic-chest-storage]", "subgroup": "g", "group": "logistics", "stackSize": 50, "type": "logistic-container", "tileWidth": 1, "tileHeight": 1 },
    { "name": "logistic-robot", "order": "a[robot]-a[logistic-robot]", "subgroup": "g", "group": "logistics", "stackSize": 50, "type": "logistic-robot", "tileWidth": 0, "tileHeight": 0 },
    { "name": "logistic-science-pack", "order": "b[logistic-science-pack]", "subgroup": "h", "group": "intermediate-products", "stackSize": 200, "type": "tool" },
    { "name": "long-handed-inserter", "order": "c[long-handed-inserter]", "subgroup": "c", "group": "logistics", "stackSize": 50, "type": "inserter", "tileWidth": 1, "tileHeight": 1 },
    { "name": "low-density-structure", "order": "o[low-density-structure]", "subgroup": "g", "group": "intermediate-products", "stackSize": 10, "type": "item" },
    { "name": "lubricant", "order": "e[lubricant]", "subgroup": "a", "group": "fluids", "type": "fluid" },
    { "name": "medium-electric-pole", "order": "a[energy]-b[medium-electric-pole]", "subgroup": "d", "group": "logistics", "stackSize": 50, "type": "electric-pole", "tileWidth": 1, "tileHeight": 1 },
    { "name": "military-science-pack", "order": "c[military-science-pack]", "subgroup": "h", "group": "intermediate-products", "stackSize": 200, "type": "tool" },
    { "name": "modular-armor", "order": "c[modular-armor]", "subgroup": "d", "group": "combat", "stackSize": 1, "type": "armor" },
    { "name": "night-vision-equipment", "order": "f[night-vision]-a[night-vision-equipment]", "subgroup": "e", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "nuclear-fuel", "order": "q[uranium-rocket-fuel]", "subgroup": "g", "group": "intermediate-products", "stackSize": 1, "type": "item" },
    { "name": "nuclear-reactor", "order": "f[nuclear-energy]-a[reactor]", "subgroup": "b", "group": "production", "stackSize": 10, "type": "reactor", "tileWidth": 5, "tileHeight": 5 },
    { "name": "offshore-pump", "order": "b[fluids]-a[offshore-pump]", "subgroup": "c", "group": "production", "stackSize": 20, "type": "offshore-pump", "tileWidth": 1, "tileHeight": 1 },
    { "name": "oil-refinery", "order": "d[refinery]", "subgroup": "e", "group": "production", "stackSize": 10, "type": "assembling-machine", "tileWidth": 5, "tileHeight": 5 },
    { "name": "personal-laser-defense-equipment", "order": "b[active-defense]-a[personal-laser-defense-equipment]", "subgroup": "f", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "personal-roboport-equipment", "order": "e[robotics]-a[personal-roboport-equipment]", "subgroup": "e", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "personal-roboport-mk2-equipment", "order": "e[robotics]-b[personal-roboport-mk2-equipment]", "subgroup": "e", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "petroleum-gas", "order": "a[fluid]-e[petroleum-gas]", "subgroup": "a", "group": "fluids", "type": "fluid" },
    { "name": "piercing-rounds-magazine", "order": "a[basic-clips]-b[piercing-rounds-magazine]", "subgroup": "b", "group": "combat", "stackSize": 200, "type": "ammo" },
    { "name": "piercing-shotgun-shell", "order": "b[shotgun]-b[piercing]", "subgroup": "b", "group": "combat", "stackSize": 200, "type": "ammo" },
    { "name": "pipe", "order": "a[pipe]-a[pipe]", "subgroup": "d", "group": "logistics", "stackSize": 100, "type": "pipe", "tileWidth": 1, "tileHeight": 1 },
    { "name": "pipe-to-ground", "order": "a[pipe]-b[pipe-to-ground]", "subgroup": "d", "group": "logistics", "stackSize": 50, "type": "pipe-to-ground", "tileWidth": 1, "tileHeight": 1 },
    { "name": "pistol", "order": "a[basic-clips]-a[pistol]", "subgroup": "a", "group": "combat", "stackSize": 5, "type": "gun" },
    { "name": "plastic-bar", "order": "f[plastic-bar]", "subgroup": "c", "group": "intermediate-products", "stackSize": 100, "type": "item" },
    { "name": "poison-capsule", "order": "b[poison-capsule]", "subgroup": "c", "group": "combat", "stackSize": 100, "type": "capsule" },
    { "name": "power-armor", "order": "d[power-armor]", "subgroup": "d", "group": "combat", "stackSize": 1, "type": "armor" },
    { "name": "power-armor-mk2", "order": "e[power-armor-mk2]", "subgroup": "d", "group": "combat", "stackSize": 1, "type": "armor" },
    { "name": "power-switch", "order": "d[other]-a[power-switch]", "subgroup": "h", "group": "logistics", "stackSize": 50, "type": "power-switch", "tileWidth": 2, "tileHeight": 2 },
    { "name": "processing-unit", "order": "g[processing-unit]", "subgroup": "g", "group": "intermediate-products", "stackSize": 100, "type": "item" },
    { "name": "production-science-pack", "order": "e[production-science-pack]", "subgroup": "h", "group": "intermediate-products", "stackSize": 200, "type": "tool" },
    { "name": "productivity-module", "order": "c[productivity]-a[productivity-module-1]", "subgroup": "f", "group": "production", "stackSize": 50, "type": "module" },
    { "name": "productivity-module-2", "order": "c[productivity]-b[productivity-module-2]", "subgroup": "f", "group": "production", "stackSize": 50, "type": "module" },
    { "name": "productivity-module-3", "order": "c[productivity]-c[productivity-module-3]", "subgroup": "f", "group": "production", "stackSize": 50, "type": "module" },
    { "name": "programmable-speaker", "order": "d[other]-b[programmable-speaker]", "subgroup": "h", "group": "logistics", "stackSize": 50, "type": "programmable-speaker", "tileWidth": 1, "tileHeight": 1 },
    { "name": "pump", "order": "b[pipe]-c[pump]", "subgroup": "d", "group": "logistics", "stackSize": 50, "type": "pump", "tileWidth": 1, "tileHeight": 2 },
    { "name": "pumpjack", "order": "b[fluids]-b[pumpjack]", "subgroup": "c", "group": "production", "stackSize": 20, "type": "mining-drill", "tileWidth": 3, "tileHeight": 3 },
    { "name": "radar", "order": "d[radar]-a[radar]", "subgroup": "g", "group": "combat", "stackSize": 50, "type": "radar", "tileWidth": 3, "tileHeight": 3 },
    { "name": "rail", "order": "a[train-system]-a[rail]", "subgroup": "e", "group": "logistics", "stackSize": 100, "type": "straight-rail", "tileWidth": 2, "tileHeight": 2 },
    { "name": "rail-chain-signal", "order": "a[train-system]-e[rail-signal-chain]", "subgroup": "e", "group": "logistics", "stackSize": 50, "type": "rail-chain-signal", "tileWidth": 1, "tileHeight": 1 },
    { "name": "rail-signal", "order": "a[train-system]-d[rail-signal]", "subgroup": "e", "group": "logistics", "stackSize": 50, "type": "rail-signal", "tileWidth": 1, "tileHeight": 1 },
    { "name": "raw-fish", "order": "h[raw-fish]", "subgroup": "b", "group": "intermediate-products", "stackSize": 100, "type": "capsule" },
    { "name": "red-wire", "order": "b[wires]-a[red-wire]", "subgroup": "h", "group": "logistics", "stackSize": 200, "type": "item" },
    { "name": "refined-concrete", "order": "b[concrete]-c[refined]", "subgroup": "i", "group": "logistics", "stackSize": 100, "type": "item" },
    { "name": "refined-hazard-concrete", "order": "b[concrete]-d[refined-hazard]", "subgroup": "i", "group": "logistics", "stackSize": 100, "type": "item" },
    { "name": "repair-pack", "order": "b[repair]-a[repair-pack]", "subgroup": "a", "group": "production", "stackSize": 100, "type": "repair-tool" },
    { "name": "roboport", "order": "c[signal]-a[roboport]", "subgroup": "g", "group": "logistics", "stackSize": 10, "type": "roboport", "tileWidth": 4, "tileHeight": 4 },
    { "name": "rocket", "order": "d[rocket-launcher]-a[basic]", "subgroup": "b", "group": "combat", "stackSize": 200, "type": "ammo" },
    { "name": "rocket-control-unit", "order": "n[rocket-control-unit]", "subgroup": "g", "group": "intermediate-products", "stackSize": 10, "type": "item" },
    { "name": "rocket-fuel", "order": "p[rocket-fuel]", "subgroup": "g", "group": "intermediate-products", "stackSize": 10, "type": "item" },
    { "name": "rocket-launcher", "order": "d[rocket-launcher]", "subgroup": "a", "group": "combat", "stackSize": 5, "type": "gun" },
    { "name": "rocket-part", "order": "q[rocket-part]", "subgroup": "g", "group": "intermediate-products", "stackSize": 5, "type": "item" },
    { "name": "rocket-silo", "order": "e[rocket-silo]", "subgroup": "g", "group": "production", "stackSize": 1, "type": "rocket-silo", "tileWidth": 9, "tileHeight": 9 },
    { "name": "satellite", "order": "m[satellite]", "subgroup": "g", "group": "production", "stackSize": 1, "type": "item" },
    { "name": "shotgun", "order": "b[shotgun]-a[basic]", "subgroup": "a", "group": "combat", "stackSize": 5, "type": "gun" },
    { "name": "shotgun-shell", "order": "b[shotgun]-a[basic]", "subgroup": "b", "group": "combat", "stackSize": 200, "type": "ammo" },
    { "name": "slowdown-capsule", "order": "c[slowdown-capsule]", "subgroup": "c", "group": "combat", "stackSize": 100, "type": "capsule" },
    { "name": "small-electric-pole", "order": "a[energy]-a[small-electric-pole]", "subgroup": "d", "group": "logistics", "stackSize": 50, "type": "electric-pole", "tileWidth": 1, "tileHeight": 1 },
    { "name": "small-lamp", "order": "a[light]-a[small-lamp]", "subgroup": "h", "group": "logistics", "stackSize": 50, "type": "lamp", "tileWidth": 1, "tileHeight": 1 },
    { "name": "solar-panel", "order": "d[solar-panel]-a[solar-panel]", "subgroup": "b", "group": "production", "stackSize": 50, "type": "solar-panel", "tileWidth": 3, "tileHeight": 3 },
    { "name": "solar-panel-equipment", "order": "a[energy-source]-a[solar-panel]", "subgroup": "e", "group": "combat", "stackSize": 20, "type": "item" },
    { "name": "solid-fuel", "order": "c[solid-fuel]", "subgroup": "c", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "space-science-pack", "order": "g[space-science-pack]", "subgroup": "h", "group": "intermediate-products", "stackSize": 2000, "type": "tool" },
    { "name": "speed-module", "order": "a[speed]-a[speed-module-1]", "subgroup": "f", "group": "production", "stackSize": 50, "type": "module" },
    { "name": "speed-module-2", "order": "a[speed]-b[speed-module-2]", "subgroup": "f", "group": "production", "stackSize": 50, "type": "module" },
    { "name": "speed-module-3", "order": "a[speed]-c[speed-module-3]", "subgroup": "f", "group": "production", "stackSize": 50, "type": "module" },
    { "name": "spidertron", "order": "b[personal-transport]-c[spidertron]-a[spider]", "subgroup": "f", "group": "logistics", "stackSize": 1, "type": "spider-vehicle", "tileWidth": 2, "tileHeight": 2 },
    { "name": "spidertron-remote", "order": "b[personal-transport]-c[spidertron]-b[remote]", "subgroup": "f", "group": "logistics", "stackSize": 1, "type": "spidertron-remote" },
    { "name": "splitter", "order": "c[splitter]-a[splitter]", "subgroup": "b", "group": "logistics", "stackSize": 50, "type": "splitter", "tileWidth": 2, "tileHeight": 1 },
    { "name": "stack-filter-inserter", "order": "g[stack-filter-inserter]", "subgroup": "c", "group": "logistics", "stackSize": 50, "type": "inserter", "tileWidth": 1, "tileHeight": 1 },
    { "name": "stack-inserter", "order": "f[stack-inserter]", "subgroup": "c", "group": "logistics", "stackSize": 50, "type": "inserter", "tileWidth": 1, "tileHeight": 1 },
    { "name": "steam", "order": "a[fluid]-b[steam]", "subgroup": "a", "group": "fluids", "type": "fluid" },
    { "name": "steam-engine", "order": "b[steam-power]-b[steam-engine]", "subgroup": "b", "group": "production", "stackSize": 10, "type": "generator", "tileWidth": 3, "tileHeight": 5 },
    { "name": "steam-turbine", "order": "f[nuclear-energy]-d[steam-turbine]", "subgroup": "b", "group": "production", "stackSize": 10, "type": "generator", "tileWidth": 3, "tileHeight": 5 },
    { "name": "steel-chest", "order": "a[items]-c[steel-chest]", "subgroup": "a", "group": "logistics", "stackSize": 50, "type": "container", "tileWidth": 1, "tileHeight": 1 },
    { "name": "steel-furnace", "order": "b[steel-furnace]", "subgroup": "d", "group": "production", "stackSize": 50, "type": "furnace", "tileWidth": 2, "tileHeight": 2 },
    { "name": "steel-plate", "order": "d[steel-plate]", "subgroup": "c", "group": "intermediate-products", "stackSize": 100, "type": "item" },
    { "name": "stone", "order": "d[stone]", "subgroup": "b", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "stone-brick", "order": "a[stone-brick]", "subgroup": "i", "group": "logistics", "stackSize": 100, "type": "item" },
    { "name": "stone-furnace", "order": "a[stone-furnace]", "subgroup": "d", "group": "production", "stackSize": 50, "type": "furnace", "tileWidth": 2, "tileHeight": 2 },
    { "name": "stone-wall", "order": "a[stone-wall]-a[stone-wall]", "subgroup": "g", "group": "combat", "stackSize": 100, "type": "wall", "tileWidth": 1, "tileHeight": 1 },
    { "name": "storage-tank", "order": "b[fluid]-a[storage-tank]", "subgroup": "a", "group": "logistics", "stackSize": 50, "type": "storage-tank", "tileWidth": 3, "tileHeight": 3 },
    { "name": "submachine-gun", "order": "a[basic-clips]-b[submachine-gun]", "subgroup": "a", "group": "combat", "stackSize": 5, "type": "gun" },
    { "name": "substation", "order": "a[energy]-d[substation]", "subgroup": "d", "group": "logistics", "stackSize": 50, "type": "electric-pole", "tileWidth": 2, "tileHeight": 2 },
    { "name": "sulfur", "order": "g[sulfur]", "subgroup": "c", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "sulfuric-acid", "order": "a[fluid]-f[sulfuric-acid]", "subgroup": "a", "group": "fluids", "type": "fluid" },
    { "name": "tank", "order": "b[personal-transport]-b[tank]", "subgroup": "f", "group": "logistics", "stackSize": 1, "type": "car", "tileWidth": 2, "tileHeight": 3 },
    { "name": "train-stop", "order": "a[train-system]-c[train-stop]", "subgroup": "e", "group": "logistics", "stackSize": 10, "type": "train-stop", "tileWidth": 2, "tileHeight": 2 },
    { "name": "transport-belt", "order": "a[transport-belt]-a[transport-belt]", "subgroup": "b", "group": "logistics", "stackSize": 100, "type": "transport-belt", "tileWidth": 1, "tileHeight": 1 },
    { "name": "underground-belt", "order": "b[underground-belt]-a[underground-belt]", "subgroup": "b", "group": "logistics", "stackSize": 50, "type": "underground-belt", "tileWidth": 1, "tileHeight": 1 },
    { "name": "uranium-235", "order": "r[uranium-235]", "subgroup": "g", "group": "intermediate-products", "stackSize": 100, "type": "item" },
    { "name": "uranium-238", "order": "r[uranium-238]", "subgroup": "g", "group": "intermediate-products", "stackSize": 100, "type": "item" },
    { "name": "uranium-cannon-shell", "order": "d[cannon-shell]-c[uranium]", "subgroup": "b", "group": "combat", "stackSize": 200, "type": "ammo" },
    { "name": "uranium-fuel-cell", "order": "r[uranium-processing]-a[uranium-fuel-cell]", "subgroup": "g", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "uranium-ore", "order": "g[uranium-ore]", "subgroup": "b", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "uranium-rounds-magazine", "order": "a[basic-clips]-c[uranium-rounds-magazine]", "subgroup": "b", "group": "combat", "stackSize": 200, "type": "ammo" },
    { "name": "used-up-uranium-fuel-cell", "order": "r[used-up-uranium-fuel-cell]", "subgroup": "g", "group": "intermediate-products", "stackSize": 50, "type": "item" },
    { "name": "utility-science-pack", "order": "f[utility-science-pack]", "subgroup": "h", "group": "intermediate-products", "stackSize": 200, "type": "tool" },
    { "name": "water", "order": "a[fluid]-a[water]", "subgroup": "a", "group": "fluids", "type": "fluid" },
    { "name": "wood", "order": "a[wood]", "subgroup": "b", "group": "intermediate-products", "stackSize": 100, "type": "item" },
    { "name": "wooden-chest", "order": "a[items]-a[wooden-chest]", "subgroup": "a", "group": "logistics", "stackSize": 50, "type": "container", "tileWidth": 1, "tileHeight": 1 }
]