export const ICON_ALTERNATES = {
    ["kr"]: [
        "iron-plate",
        "iron-gear-wheel",
        "steel-plate",
        "copper-plate",
        "electronic-circuit",
        "advanced-circuit",
        "logistic-science-pack",
        "automation-science-pack",
        "military-science-pack",
        "utility-science-pack",
        "production-science-pack",
        "chemical-science-pack",
        "space-science-pack",
        "heavy-oil",
        "heavy-oil-cracking",
        "light-oil",
        "light-oil-cracking",
        "lubricant",
        "crude-oil"
    ],
    ["se"]: [
        "energy-shield-mk1-equipment",
        "energy-shield-mk2-equipment",
        "energy-shield-mk3-equipment",
        "energy-shield-mk4-equipment",
        "speed-module",
        "speed-module-2",
        "speed-module-3",
        "productivity-module",
        "productivity-module-2",
        "productivity-module-3",
        "effectivity-module",
        "effectivity-module-2",
        "effectivity-module-3",
    ],
    ["aai"]: [
        "stone-wall",
        "steel-chest",
        "engine-unit",
        "electric-engine-unit",
    ]
}